### ISSUE TITLE
Weird scrollbars on Chrome/Mac in online editor

### ISSUE THREAD

**Issue by pronebird** [js2coffee/js2coffee-redux#5]
It looks weird, I have two scrollbars now for each direction:

![image](https://cloud.githubusercontent.com/assets/704044/5889622/3c71a01e-a431-11e4-80cf-aac281c720c9.png)

Is this some sort of Mac/Chrome thing?

Quick hack worked fine:

``` css
/* Remove white scrollbars */
.CodeMirror-scroll {
    overflow: hidden !important;
}

/* Remove some weird square in the corner of scrollbars */
.CodeMirror-scrollbar-filler {
    display: none;
}
```

You can inject CSS from console using the following snippet:

``` js
var s = document.createElement('STYLE');
s.innerText = '.CodeMirror-scroll { overflow: hidden !important; } .CodeMirror-scrollbar-filler { display: none; }';
document.body.appendChild(s);
```
